# Generated by Django 5.0.6 on 2024-05-23 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Laptop', 'Asus'), ('Desktop', 'Dell'), ('Mouse', 'Rog'), ('Keyboard', 'Logitech')], max_length=100)),
            ],
        ),
    ]
