# Generated by Django 5.0.6 on 2024-06-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahesh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computervarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
