# Generated by Django 5.0.6 on 2024-06-05 06:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahesh', '0003_alter_computervarity_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(default=django.utils.timezone.now)),
                ('computer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='mahesh.computervarity')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('comment', models.TextField(default='No Comment Available')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mahesh.computervarity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('computer_varieties', models.ManyToManyField(related_name='stores', to='mahesh.computervarity')),
            ],
        ),
    ]
